extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

image:
  repository: otel/opentelemetry-collector
  tag: 0.91.0

# mode: daemonset
mode: deployment

config:
  exporters:
    otlp:
      endpoint: otel-collector-standalone-opentelemetry-collector:4317
      tls:
        insecure: true
    logging:
      loglevel: debug
  processors:
    resource:
      attributes:
        - key: k8s.node.name
          value: ${NODE_NAME}
          action: upsert
  service:
    pipelines:
      logs:
        exporters:
          - otlp
          - logging
        processors:
          - batch
          - memory_limiter
          - resource
      metrics:
        exporters:
          - otlp
          - logging
        processors:
          - batch
          - memory_limiter
          - resource
      traces:
        exporters:
          - otlp
          - logging
        processors:
          - batch
          - memory_limiter
          - resource
